services:
  common-ros:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_DISTRO=humble
      
    # common environment variables
    environment:
    # ROS
    - ROS_DOMAIN_ID=5  
    # DDS 
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

    # capabilities
    privileged: true

    # commont mounts
    volumes:
      # sync source dir
      - ../../src/:/root/ws/src
      # syncd devcontainer dir
      - ../../.devcontainer/:/root/ws/.devcontainer

    # default entrypoint command
    command: sleep infinity

    